import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faAddressBook,
    faArrowLeft,
    faBars,
    faCalendarDays,
    faCheck,
    faClipboardCheck,
    faChevronDown,
    faCircleExclamation,
    faCircleInfo,
    faEllipsis,
    faFolderOpen,
    faGear,
    faGripLines,
    faHouse,
    faIdCard,
    faInbox,
    faLock,
    faLockOpen,
    faMagnifyingGlass,
    faMusic,
    faPen,
    faPencil,
    faPlus,
    faStar,
    faStore,
    faTag,
    faTrash,
    faTrashCan,
    faUser,
    faUsers,
    faXmark,
} from '@fortawesome/free-solid-svg-icons';

/**
 * Curated Font Awesome Free icons for the UI kit.
 * Add icons here as needed — do not import entire fas/far/fab packs.
 */
export const kitIcons = [
    faAddressBook,
    faArrowLeft,
    faBars,
    faCalendarDays,
    faCheck,
    faClipboardCheck,
    faChevronDown,
    faCircleExclamation,
    faCircleInfo,
    faEllipsis,
    faFolderOpen,
    faGear,
    faGripLines,
    faHouse,
    faIdCard,
    faInbox,
    faLock,
    faLockOpen,
    faMagnifyingGlass,
    faMusic,
    faPen,
    faPencil,
    faPlus,
    faStar,
    faStore,
    faTag,
    faTrash,
    faTrashCan,
    faUser,
    faUsers,
    faXmark,
];

library.add(...kitIcons);
